version: '3.7'

services:
  mark-admin:
    image: khoavhd/konsept:latest
    ports:
      - 8888:8888
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure
