version: '3.7'

services:
  be:
    image: khoavhd/konsept:latest
    ports:
      - target: 8888
        published: 8888
        mode: host
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure
