name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
#2
env:
  REGISTRY: registry.hub.docker.com/khoavhd
  DOCKER_USERNAME: khoavhd
  IMAGE_NAME: konsept
  EXPOSE_PORT: 8888

#3
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build container image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/$(echo $IMAGE_NAME) .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image to Container Registry
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$(echo $IMAGE_NAME)

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    # TODO: change to docker swarm for server down issue during deployment
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME,REGISTRY,{{ secrets.DOCKER_HUB_USERNAME }}, {{ secrets.DOCKER_HUB_TOKEN }},GITHUB_SHA, EXPOSE_PORT
          script: |
            # Login to registry
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
            # Stop running container
            docker stop $(echo $IMAGE_NAME)
            # Remove old container
            docker rm $(echo $IMAGE_NAME)
            # Run a new container from a new image
            docker run -d \
            --restart always \
            -p $(echo $EXPOSE_PORT):$(echo $EXPOSE_PORT) \
            --name $(echo $IMAGE_NAME) \
            ${{ secrets.DOCKER_HUB_USERNAME }}/$(echo $IMAGE_NAME)
